services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: kencur_app
    restart: unless-stopped
    working_dir: /var/www
    depends_on:
      - mysql
    volumes:
      - ./:/var/www
    networks:
      - kencur_network

  nginx:
    image: nginx:alpine
    container_name: kencur_app_nginx
    restart: unless-stopped
    ports:
      - "8004:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - kencur_network

  mysql:
    image: mysql:8.0
    container_name: kencur_app_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - kencur_network

volumes:
  mysql_data:

networks:
  kencur_network:
    driver: bridge